### ISSUE TITLE
How can I run nasim:Medium-v0 correctly?

### ISSUE THREAD

**Issue by Garytoner** [seolhokim/DistributedRL-Pytorch-Ray#10]
Thank you for your contribution,the  code is very good,but when I try to run some complex environment like nasim:Medium-v0 , the trajectory length will reach step limit.I will very appreciate if you can run the environment mentioned above when you have some time,Thank you very much!

**Comment by seolhokim** [comment]
Thanks for the kind words. How about adjusting traj_length in config.ini?

**Comment by Garytoner** [comment]
Tank you for answering my question,I haved tried to adjust traj_length to 128,but it doesn't work.But I have sloved the problem by using another neural network，it work well when I run  CartPole-v0.But I face another problem, when I run nasim:Medium-v0,the trajectory length is random,it  doesn't reach convergence.The  compute gredient function may be not prefect,I tried other algorithms like https://github.com/wisnunugroho21/asynchronous_impala_PPO,It have the same  problem。Another question is  that the DPPO is asynchronous PPO or synchronous PPO?In config.ini ,for dppo, the asynchronous is False,I am confused.

**Comment by seolhokim** [comment]
DPPO is Distributed PPO in [Emergence of Locomotion Behaviours in Rich Environments](https://arxiv.org/abs/1707.02286). It is not a asynchronous algorithm. 

I don't know nasim environment but Cartpole is also not fixed trajectory length environment.

**Comment by Garytoner** [comment]
Thank you very much ! Is APPO（Asynchronous PPO） another form of distributed PPO？How can I change the DPPO in 
DistributedRL-Pytorch-Ray to APPO? Will it be easy？

**Comment by seolhokim** [comment]
Why would you change it to APPO?

**Comment by Garytoner** [comment]
It maybe faster.

**Comment by seolhokim** [comment]
There are some asynchronous algorithms(a3c, impala, apex) in this repository. It would be easier for you to make it by referring to it.

**Comment by Garytoner** [comment]
Thank you very much!
