### ISSUE TITLE
the code is good,but my a3c or ppo are not working in Acrobot-v1 test

### ISSUE THREAD

**Issue by qfxdz** [seolhokim/DistributedRL-Pytorch-Ray#9]
think you for this good work,but i have some problem, why i can not train in acrobot-v1

**Comment by seolhokim** [comment]
Thanks for the kind words. It seems all learner and actor works well, but I don't know why it can't learn well exactly. This problem may occur due to hyperparameter differences, but it seems not to be this problem because it cannot be learned at all.

**Comment by qfxdz** [comment]
i have test impala in 32gpus ,it can run sucess,but tensorboard can not use ,because it can not serializable,  so i change it to  wtire alone and can run, thinks for you work

**Comment by seolhokim** [comment]
Could you create pull request for that?

**Comment by qfxdz** [comment]
oo, yes, i close this
